include($(IMTCOREDIR)/Config/QMake/ImtCore.pri)

INCLUDEPATH += $(AGENTINODIR)/Include
INCLUDEPATH += $(AGENTINODIR)/Impl
INCLUDEPATH += $(AGENTINODIR)/$$AUXINCLUDEDIR

LIBS += -L$$PWD/../../Lib/$$COMPILER_DIR

