TARGET = agentinogql

include($(ACFDIR)/Config/QMake/StaticConfig.pri)
include($(ACFDIR)/Config/QMake/AcfQt.pri)
include($(IMTCOREDIR)/Config/QMake/ImtCore.pri)

# SDL
include($(IMTCOREDIR)/Config/QMake/SdlCodeGenerator.pri)

# SDL
# SDL_GENERATOR_SCHEME_NAME = APIv1_0
# SDL_GENERATOR_SCHEME_PATH = $$PWD/../SDL/APIv1_0.sdl
# SDL_GENERATOR_CPP_OUT_SUBFOLDER = $$OUT_PWD/$$AUXINCLUDEPATH/GeneratedFiles/$$TARGET/SDL/CPP
# SDL_GENERATOR_CPP_NAMESPACE = "$$TARGET::sdl"
# SDL_GENERATOR_QML_OUT_SUBFOLDER = $$OUT_PWD/$$AUXINCLUDEPATH/GeneratedFiles/$$TARGET/SDL/QML
# SDL_GENERATOR_QML_MODULE_NAME = $${TARGET}Sdl

# SDL_GENERATOR_SCHEME_PATH = $$PWD/../SDL/APIv1_0.sdl
# SDL_CPP_COMPILER = $$CreateCppQmlSdlTarget(APIv1_0, $$SDL_GENERATOR_SCHEME_PATH)
# $${SDL_CPP_COMPILER}.input = SDL_GENERATOR_SCHEME_PATH
# QMAKE_EXTRA_COMPILERS += $${SDL_CPP_COMPILER}

