TARGET = agentinosdl

include($(ACFDIR)/Config/QMake/StaticConfig.pri)
include($(IMTCOREDIR)/Config/QMake/ImtCore.pri)


# SDL
include($(IMTCOREDIR)/Config/QMake/SdlCodeGenerator.pri)

SDL_GENERATOR_AGENTS_SCHEME_PATH = $$PWD/../1.0/Agents.sdl
SDL_CPP_AGENTS_COMPILER = $$CreateCppQmlSdlTarget(Agents, $$SDL_GENERATOR_AGENTS_SCHEME_PATH)
$${SDL_CPP_AGENTS_COMPILER}.input = SDL_GENERATOR_AGENTS_SCHEME_PATH
QMAKE_EXTRA_COMPILERS += $${SDL_CPP_AGENTS_COMPILER}

SDL_GENERATOR_SERVICES_SCHEME_PATH = $$PWD/../1.0/Services.sdl
SDL_CPP_SERVICES_COMPILER = $$CreateCppQmlSdlTarget(Services, $$SDL_GENERATOR_SERVICES_SCHEME_PATH)
$${SDL_CPP_SERVICES_COMPILER}.input = SDL_GENERATOR_SERVICES_SCHEME_PATH
QMAKE_EXTRA_COMPILERS += $${SDL_CPP_SERVICES_COMPILER}

SDL_GENERATOR_TOPOLOGY_SCHEME_PATH = $$PWD/../1.0/Topology.sdl
SDL_CPP_TOPOLOGY_COMPILER = $$CreateCppQmlSdlTarget(Topology, $$SDL_GENERATOR_TOPOLOGY_SCHEME_PATH)
$${SDL_CPP_TOPOLOGY_COMPILER}.input = SDL_GENERATOR_TOPOLOGY_SCHEME_PATH
QMAKE_EXTRA_COMPILERS += $${SDL_CPP_TOPOLOGY_COMPILER}

SDL_LOG_SCHEME_PATH = $$PWD/../1.0/ServiceLog.sdl
SDL_CPP_LOG_COMPILER = $$CreateCppQmlSdlTarget(ServiceLog, $$SDL_LOG_SCHEME_PATH)
$${SDL_CPP_LOG_COMPILER}.input = SDL_LOG_SCHEME_PATH
QMAKE_EXTRA_COMPILERS += $${SDL_CPP_LOG_COMPILER}

